Sprint 5/step 1
Avanire/react-burger pull request #8
Opened 2023-01-25 14:57 UTC by Avanire

2023-01-25 15:20 UTC, andryxxa93 requested changes
Отличная работа! Сокет соединения настроены и работают корректно. Открываются и закрываются когда нужно.
Что понравилось:
- Хорошо типизировали хуки и хранилище
- Использовали модификаторы доступа
- Не использовали `any` и `ts-ignore`

Что необходимо исправить:
- Есть открыть конкретный заказ из "Истории заказов" по прямой ссылке, то получаем вечный лоадер. 

https://user-images.githubusercontent.com/60173362/214602256-99638e1c-eccf-4ca5-a152-54975f0f6876.mov

Удачи!

2023-01-27 06:00 UTC, andryxxa93 requested changes
С открытием заказа теперь всё отлично. Обнаружилась другая небольшая проблема - у вас дублируется запрос на получение номера заказа. Исправьте этот момент и я сразу же приму вашу работу.

https://user-images.githubusercontent.com/60173362/215019784-1f1cd0a1-b31e-4b78-93a0-b7d832586ef9.mov

2023-01-27 09:09 UTC, Avanire commented
> С открытием заказа теперь всё отлично. Обнаружилась другая небольшая проблема - у вас дублируется запрос на получение номера заказа. Исправьте этот момент и я сразу же приму вашу работу.
> 2023-01-27.08.58.27.mov

Предполагаю, что это происходит из-за того что React.StrictMode выполняет рендринг 2 раза в режиме development, в production такого не будет и заказ будет отправляться 1 раз. Действительно стоит исправлять это?

2023-01-27 12:44 UTC, andryxxa93 commented
Да, причина в этом. Я приму вашу работу, но для стабильного прохождения следующих этапов рекомендую этот момент подправить.

2023-01-28 05:16 UTC, merged